In [ ]:
def chk(a):
 if a % 25 == 0:
     return True
 else:
     print("Not Divisible")

In [ ]:
i = '20'
if i > 20:
    print(1)
else:
    print(2)

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
a = 1
for i in range(1,6):
     a = a*i
print(a)

120

In [ ]:
list_mul = ['2','2','2']
list_mul*2

['2', '2', '2', '2', '2', '2']

In [ ]:
vec = np.arange(10, 20, 3)
print(vec)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
vec = np.arange(10, 20, 3)
print(vec)

[10 13 16 19]

In [ ]:
import numpy as np
vec = np.linspace(10, 20, 3)
print(vec)

[10. 15. 20.]

In [ ]:
import numpy as np
vec = np.zeros([2,3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
import numpy as np
vec = np.arange(0,5)
print(vec.reshape((2,3)))

ValueError: cannot reshape array of size 5 into shape (2,3)

In [ ]:
import numpy as np
vec1 = [10,15,20]
vec2 = [15,25,35]
print(vec1+vec2)

[10, 15, 20, 15, 25, 35]

In [ ]:
import numpy as np
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1 + vec2)

ValueError: operands could not be broadcast together with shapes (4,) (3,)

In [ ]:
import numpy as np
vec = np.arange(2,5,1)
print(1/vec)
print(vec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]

In [ ]:
import numpy as np
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]

/tmp/ipykernel_1228/1490648484.py:4: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)

In [ ]:
import numpy as np
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]

/tmp/ipykernel_1228/1490648484.py:4: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)

In [ ]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5

In [ ]:
import numpy as np
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]

In [ ]:
import numpy as np
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]

In [ ]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]

In [ ]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1

In [ ]:
import numpy as np
mat1 = np.arange(-9,0,1).reshape(3,3)
print(np.min(mat1))
print(np.max(mat1))

-9
-1

In [ ]:
import pandas as pd
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
print(temp_data[:2])

day1    31
day2    28
dtype: int64

In [ ]:
import pandas as pd
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
print(temp_data['day3'])

30

In [ ]:
import pandas as pd
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
print(temp_data[:-2])

day1    31
day2    28
dtype: int64

In [ ]:
import pandas as pd
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)
print(temp_data[2:])

day3    30
day4    32
dtype: int64

In [ ]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
print(calorie_data[:2])

    day  calories  duration_min
0  day1       450            30
1  day2       300            25

In [ ]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
print(calorie_data['calories'])

0    450
1    300
2    345
3    520
4    600
Name: calories, dtype: int64

In [ ]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
print(calorie_data[::2])

    day  calories  duration_min
0  day1       450            30
2  day3       345            29
4  day5       600            48

In [1]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
print(calorie_data.loc[0])

day             day1
calories         450
duration_min      30
Name: 0, dtype: object

In [2]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data.iloc[[1,2],[1]]

   calories
1       300
2       345

In [3]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data.loc[[1,2],['calories']]

   calories
1       300
2       345

In [5]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data.loc[calorie_data['calories']>500]

    day  calories  duration_min
3  day4       520            39
4  day5       600            48

In [9]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
print(calorie_data.drop('duration_min', axis = 1))

    day  calories
0  day1       450
1  day2       300
2  day3       345
3  day4       520
4  day5       600

In [12]:
import pandas as pd
import datetime
date = datetime.date(2022, 1, 29)
print(date)
print(date.month)

2022-01-29
1